name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.8
  - conda-forge::requests=2.24.0
  - conda-forge::pip=20.3.3
  - conda-forge::mlflow=12.2.2
  - conda-forge::hydra-core
  - pip:
      - wandb==0.12.17
      - hydra-joblib-launcher
