name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.8
  - conda-forge::pandas
  - conda-forge::pip=20.3.3
  - conda-forge::pytest=6.2.2
  - conda-forge::scipy=1.6.1
  - pip:
      - wandb==0.12.17