name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - pip=23.2.1
  - scikit-learn=0.24.1
  - matplotlib
  - plotly
  - pillow
  - mlflow=2.2.2
  - pip:
      - wandb==0.12.17
      - omegaconf